import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import mysql from 'mysql2/promise';
const app=express();
const pool=mysql.createPool({host:process.env.DB_HOST||'127.0.0.1',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'vibechecks',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'vibechecks',waitForConnections:true,connectionLimit:10,decimalNumbers:true});
app.use(helmet({contentSecurityPolicy:false})); app.use(express.json()); app.use(express.static('dist'));
const small=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
function whole(n){if(n<20)return small[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?' '+small[n%10]:'');if(n<1000)return small[Math.floor(n/100)]+' Hundred'+(n%100?' '+whole(n%100):'');if(n<1e6)return whole(Math.floor(n/1000))+' Thousand'+(n%1000?' '+whole(n%1000):'');return whole(Math.floor(n/1e6))+' Million'+(n%1e6?' '+whole(n%1e6):'')}
function words(n){const d=Math.floor(n),c=Math.round((n-d)*100);return (whole(d)||'Zero')+' and '+String(c).padStart(2,'0')+'/100 Dollars'}
const safe=f=>async(req,res)=>{try{await f(req,res)}catch(e){console.error(e);res.status(400).json({error:e.message||'Request failed'})}};
app.get('/api/health',safe(async(q,r)=>{await pool.query('SELECT 1');r.json({ok:true})}));
app.get('/api/accounts',safe(async(q,r)=>{const[x]=await pool.query("SELECT id,nickname,account_holder,address1,address2,city,state,postal_code,bank_name,routing_number,CONCAT(REPEAT('*',GREATEST(0,LENGTH(account_number)-4)),RIGHT(account_number,4)) account_number_masked,next_check_number FROM bank_accounts ORDER BY nickname");r.json(x)}));
app.post('/api/accounts',safe(async(q,r)=>{const s=q.body;if(!s.nickname||!s.account_holder||!s.bank_name||!/^[0-9]{9}$/.test(s.routing_number||'')||!/^[0-9]{4,34}$/.test(s.account_number||''))throw Error('Invalid account details');const[x]=await pool.execute('INSERT INTO bank_accounts(nickname,account_holder,address1,address2,city,state,postal_code,bank_name,routing_number,account_number,next_check_number) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[s.nickname,s.account_holder,s.address1||null,s.address2||null,s.city||null,s.state||null,s.postal_code||null,s.bank_name,s.routing_number,s.account_number,Number(s.next_check_number)||1001]);r.status(201).json({id:x.insertId})}));
app.get('/api/payees',safe(async(q,r)=>{const[x]=await pool.query('SELECT * FROM payees ORDER BY name');r.json(x)}));
app.post('/api/payees',safe(async(q,r)=>{const s=q.body;if(!s.name)throw Error('Payee name required');const[x]=await pool.execute('INSERT INTO payees(name,address1,address2,city,state,postal_code) VALUES(?,?,?,?,?,?)',[s.name,s.address1||null,s.address2||null,s.city||null,s.state||null,s.postal_code||null]);r.status(201).json({id:x.insertId})}));
app.get('/api/checks',safe(async(q,r)=>{const[x]=await pool.query('SELECT c.*,b.nickname account_name FROM checks c JOIN bank_accounts b ON b.id=c.bank_account_id ORDER BY c.check_date DESC,c.check_number DESC LIMIT 500');r.json(x)}));
app.post('/api/checks',safe(async(q,r)=>{const s=q.body;if(!s.bank_account_id||!s.payee_name||!(Number(s.amount)>0)||!s.check_date)throw Error('Missing check fields');const cn=await pool.getConnection();try{await cn.beginTransaction();const[[a]]=await cn.execute('SELECT next_check_number FROM bank_accounts WHERE id=? FOR UPDATE',[s.bank_account_id]);if(!a)throw Error('Account not found');const amount=Number(s.amount);const[x]=await cn.execute('INSERT INTO checks(bank_account_id,payee_id,check_number,check_date,payee_name,amount,amount_words,memo) VALUES(?,?,?,?,?,?,?,?)',[s.bank_account_id,s.payee_id||null,a.next_check_number,s.check_date,s.payee_name,amount,words(amount),s.memo||null]);await cn.execute('UPDATE bank_accounts SET next_check_number=next_check_number+1 WHERE id=?',[s.bank_account_id]);await cn.commit();r.status(201).json({id:x.insertId,check_number:a.next_check_number})}catch(e){await cn.rollback();throw e}finally{cn.release()}}));
app.get('/api/checks/:id',safe(async(q,r)=>{const[[x]]=await pool.execute('SELECT c.*,b.account_holder,b.address1 payer_address1,b.address2 payer_address2,b.city payer_city,b.state payer_state,b.postal_code payer_postal,b.bank_name,b.routing_number,b.account_number FROM checks c JOIN bank_accounts b ON b.id=c.bank_account_id WHERE c.id=?',[q.params.id]);x?r.json(x):r.sendStatus(404)}));
app.post('/api/checks/:id/status',safe(async(q,r)=>{if(!['draft','printed','void','cleared'].includes(q.body.status))throw Error('Invalid status');const s=q.body.status;await pool.execute("UPDATE checks SET status=?,printed_at=IF(?='printed',NOW(),printed_at),cleared_at=IF(?='cleared',NOW(),cleared_at) WHERE id=?",[s,s,s,q.params.id]);r.json({ok:true})}));
app.listen(process.env.PORT||3001,()=>console.log('VibeChecks API listening'));