<script setup>
import{ref,onMounted,computed}from'vue';
const tab=ref('write'),accounts=ref([]),payees=ref([]),checks=ref([]),payeeChecks=ref([]),selectedPayee=ref(null),notice=ref(''),registerSearch=ref(''),registerStatus=ref(''),registerAccount=ref('');
const filteredChecks=computed(()=>checks.value.filter(c=>(!registerStatus.value||c.status===registerStatus.value)&&(!registerAccount.value||String(c.bank_account_id)===String(registerAccount.value))&&(!registerSearch.value||[c.check_number,c.payee_name,c.memo,c.account_name,c.status].some(v=>String(v??'').toLowerCase().includes(registerSearch.value.toLowerCase())))));
const form=ref({bank_account_id:'',payee_id:'',payee_name:'',amount:'',check_date:new Date().toISOString().slice(0,10),memo:''});
const account=ref({nickname:'',account_holder:'',address1:'',address2:'',city:'',state:'',postal_code:'',phone:'',email:'',date_format:'MM/DD/YYYY',bank_name:'',routing_number:'',account_number:'',next_check_number:1001});
const payee=ref({name:'',address1:'',city:'',state:'',postal_code:''});
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'Request failed')}return r.json()}
async function load(){[accounts.value,payees.value,checks.value]=await Promise.all([api('/api/accounts'),api('/api/payees'),api('/api/checks')])}
function choose(){const p=payees.value.find(x=>x.id==form.value.payee_id);form.value.payee_name=p?p.name:''}
async function showPayeeHistory(p){selectedPayee.value=p;payeeChecks.value=await api('/api/payees/'+p.id+'/checks')}
async function saveCheck(){try{const x=await api('/api/checks',{method:'POST',body:JSON.stringify({...form.value,payee_id:form.value.payee_id||null})});notice.value='Saved check #'+x.check_number;await load()}catch(e){notice.value=e.message}}
async function addAccount(){notice.value='';try{await api('/api/accounts',{method:'POST',body:JSON.stringify(account.value)});notice.value='Bank account added';account.value={nickname:'',account_holder:'',address1:'',address2:'',city:'',state:'',postal_code:'',phone:'',email:'',date_format:'MM/DD/YYYY',bank_name:'',routing_number:'',account_number:'',next_check_number:1001};await load()}catch(e){notice.value=e.message}}
async function addPayee(){try{await api('/api/payees',{method:'POST',body:JSON.stringify(payee.value)});await load()}catch(e){notice.value=e.message}}
async function status(id,s){await api('/api/checks/'+id+'/status',{method:'POST',body:JSON.stringify({status:s})});await load()}
function formatDate(value,fmt='MM/DD/YYYY'){const raw=String(value).slice(0,10),[y,m,d]=raw.split('-');if(fmt==='YYYY/MM/DD')return y+'/'+m+'/'+d;if(fmt==='DD/MM/YYYY')return d+'/'+m+'/'+y;if(fmt==='MM-DD-YYYY')return m+'-'+d+'-'+y;return m+'/'+d+'/'+y}
function exportRegister(){const rows=[['Check #','Date','Payee','Account','Memo','Amount','Status'],...filteredChecks.value.map(c=>[c.check_number,String(c.check_date).slice(0,10),c.payee_name,c.account_name,c.memo,Number(c.amount).toFixed(2),c.status])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),el=document.createElement('a');el.href=url;el.download='vibechecks-register.csv';el.click();URL.revokeObjectURL(url)}
function printRegister(){const w=open('','_blank');if(!w){notice.value='Pop-up blocked. Allow pop-ups to print.';return}const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const rows=filteredChecks.value.map(c=>'<tr><td>'+esc(c.check_number)+'</td><td>'+esc(String(c.check_date).slice(0,10))+'</td><td>'+esc(c.payee_name)+'</td><td>'+esc(c.account_name)+'</td><td>'+esc(c.memo||'')+'</td><td>$'+Number(c.amount).toFixed(2)+'</td><td>'+esc(c.status)+'</td></tr>').join('');w.document.write('<!doctype html><html><head><title>Check Register</title><style>@page{size:letter landscape;margin:.4in}body{font:10pt Arial}table{width:100%;border-collapse:collapse}th,td{padding:5px;border-bottom:1px solid #bbb;text-align:left}thead{display:table-header-group}</style></head><body><h2>VibeChecks Check Register</h2><table><thead><tr><th>#</th><th>Date</th><th>Payee</th><th>Account</th><th>Memo</th><th>Amount</th><th>Status</th></tr></thead><tbody>'+rows+'</tbody></table></body></html>');w.document.close();w.focus();setTimeout(()=>w.print(),250)}
async function printCheck(id){ const c=await api('/api/checks/'+id),w=open('','_blank');if(!w){notice.value='Pop-up blocked. Allow pop-ups to print.';return}
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const html=`<!doctype html><html><head><title>Check ${esc(c.check_number)}</title><style>
 @page{size:8.5in 11in;margin:0}*{box-sizing:border-box}html,body{margin:0!important;padding:0!important;width:8.5in!important;height:11in!important}body{font-family:Arial,sans-serif;color:#000;overflow:hidden}
 .sheet{position:relative;width:8.5in;height:11in}.check{position:absolute;left:0;top:.15in;width:8.5in;height:3.5in}.stub{position:absolute;left:0;top:3.65in;width:8.5in;height:3.5in;padding:.28in .55in;font-size:9pt}.stub-company{position:absolute;left:.55in;top:.25in;font-weight:bold;font-size:10pt}.stub-checkno{position:absolute;right:.55in;top:.22in;font-size:11pt}.stub-payee{position:absolute;left:.85in;top:.62in;font-size:10pt;font-weight:bold}.stub-grid{position:absolute;left:.55in;right:.55in;top:1.02in;display:grid;grid-template-columns:.72in .62in 1.0in 1.12in 1.12in .82in 1.05in;column-gap:.08in;text-align:right}.stub-grid>div:nth-child(1),.stub-grid>div:nth-child(2),.stub-grid>div:nth-child(3){text-align:left}.stub-label{font-size:8pt;color:#333;line-height:1.05}.stub-value{font-size:9pt;padding-top:.08in}.stub-total-label{position:absolute;right:1.65in;top:1.72in;font-size:9pt}.stub-total{position:absolute;right:.62in;top:1.72in;width:.9in;text-align:right;font-size:9pt}.stub-account{position:absolute;left:.55in;bottom:.35in;font-size:9pt}.stub-bottom-total{position:absolute;right:.62in;bottom:.35in;width:.9in;text-align:right;font-size:9pt}
 .payer{position:absolute;left:.45in;top:.20in;font-size:8pt;line-height:1.12}.bank{position:absolute;left:3.25in;top:.28in;font-size:8pt}.number{position:absolute;right:.40in;top:.25in;font-size:10pt;font-weight:bold}.date{position:absolute;right:.45in;top:.72in;font-size:9pt}
 .paylabel{position:absolute;left:.38in;top:1.12in;font-size:7pt;line-height:1.1}.payee{position:absolute;left:1.25in;right:1.55in;top:1.08in;height:.30in;border-bottom:1px solid #000;padding:.03in .08in;font-size:10pt;font-weight:bold}
 .amount{position:absolute;right:.38in;top:1.08in;width:1.12in;height:.30in;border:1px solid #000;padding:.04in .08in;text-align:right;font-size:10pt;font-weight:bold}.words{position:absolute;left:.38in;right:.38in;top:1.52in;height:.32in;border-bottom:1px solid #000;padding:.04in .08in;font-size:9pt}
 .memo{position:absolute;left:.45in;top:2.18in;font-size:8pt}.signature{position:absolute;right:.55in;top:2.30in;width:2.45in;text-align:center;font-size:7pt}.signature-line{border-top:1px solid #000;margin-bottom:.05in}.micr{position:absolute;left:.72in;bottom:.18in;font-family:E13B,OCRB,monospace;font-size:14pt;letter-spacing:.005in;white-space:nowrap}.void-stamp{position:absolute;left:1.1in;top:1.05in;width:6.3in;text-align:center;font:bold 54pt Arial,sans-serif;letter-spacing:.12in;transform:rotate(-18deg);opacity:.28;z-index:20;pointer-events:none}
 </style></head><body><div class="sheet"><div class="check">${c.status==='void'?'<div class="void-stamp">VOID</div>':''}<div class="payer"><b>${esc(c.account_holder)}</b><br>${esc(c.payer_address1||'')}${c.payer_address2?'<br>'+esc(c.payer_address2):''}${(c.payer_city||c.payer_state||c.payer_postal)?'<br>'+esc([c.payer_city,c.payer_state].filter(Boolean).join(', ')+(c.payer_postal?' '+c.payer_postal:'')):''}${c.payer_phone?'<br>'+esc(c.payer_phone):''}${c.payer_email?'<br>'+esc(c.payer_email):''}</div><div class="bank">${esc(c.bank_name)}</div><div class="number">#${esc(c.check_number)}</div><div class="date">${esc(formatDate(c.check_date,c.date_format))}</div><div class="paylabel">PAY TO THE<br>ORDER OF</div><div class="payee">${esc(c.payee_name)}</div><div class="amount">$${Number(c.amount).toFixed(2)}</div><div class="words">${esc(c.amount_words)}</div><div class="memo">Memo: ${esc(c.memo||'')}</div><div class="signature"><div class="signature-line"></div>AUTHORIZED SIGNATURE</div><div class="micr">⑆${esc(c.routing_number)}⑆ &nbsp;⑈${esc(c.account_number)}⑈ &nbsp;${esc(c.check_number)}</div></div><div class="stub"><div class="stub-title">${esc(c.account_holder)}</div><div class="stub-grid"><div class="stub-label">DATE</div><div class="stub-label">COMPANY / PAYEE</div><div class="stub-label">REFERENCE #</div><div class="stub-label">CHECK AMOUNT</div><div class="stub-value">${esc(String(c.check_date).slice(0,10))}</div><div class="stub-value">${esc(c.payee_name)}</div><div class="stub-value">${esc(c.check_number)}</div><div class="stub-value">${Number(c.amount).toFixed(2)}</div></div><div class="stub-note">Memo: ${esc(c.memo||"")}</div></div></div></body></html>`;
 w.document.write(html);w.document.close();w.focus();setTimeout(async()=>{w.print();try{await api('/api/checks/'+id+'/prints',{method:'POST'});await load()}catch(e){notice.value=e.message}},350)
}
onMounted(load)
</script>
<template><header><h1>VibeChecks</h1><nav><button v-for="x in ['write','register','accounts','payees']" @click="tab=x" :class="{active:tab===x}">{{x}}</button></nav></header><main><p class="notice" v-if="notice">{{notice}}</p>
<section v-if="tab==='write'" class="card"><h2>Write Check</h2><label>Bank account<select v-model="form.bank_account_id"><option value="">Select</option><option v-for="a in accounts" :value="a.id">{{a.nickname}} — next #{{a.next_check_number}}</option></select></label><label>Saved payee<select v-model="form.payee_id" @change="choose"><option value="">Custom</option><option v-for="p in payees" :value="p.id">{{p.name}}</option></select></label><label v-if="!form.payee_id">Pay to<input v-model="form.payee_name" placeholder="Enter custom payee"></label><label v-else>Pay to<input :value="form.payee_name" readonly></label><div class="row"><label>Amount<input type="number" step=".01" v-model="form.amount"></label><label>Date<input type="date" v-model="form.check_date"></label></div><label>Memo<input v-model="form.memo"></label><button class="primary" @click="saveCheck">Save Check</button></section>
<section v-if="tab==='register'" class="card wide"><div class="register-head"><h2>Check Register</h2><div><button @click="printRegister">Print Register</button> <button @click="exportRegister">Export CSV</button></div></div><div class="register-tools"><input v-model="registerSearch" placeholder="Search check #, payee, memo..."><select v-model="registerAccount"><option value="">All accounts</option><option v-for="a in accounts" :value="a.id">{{a.nickname}}</option></select><select v-model="registerStatus"><option value="">All statuses</option><option value="draft">Draft</option><option value="printed">Printed</option><option value="cleared">Cleared</option><option value="void">Void</option></select></div><p>{{filteredChecks.length}} checks</p><div class="table-wrap"><table><thead><tr><th>#</th><th>Date</th><th>Payee</th><th>Account</th><th>Memo</th><th>Amount</th><th>Status</th><th>Prints</th><th>Actions</th></tr></thead><tbody><tr v-for="c in filteredChecks" :key="c.id"><td>{{c.check_number}}</td><td>{{String(c.check_date).slice(0,10)}}</td><td>{{c.payee_name}}</td><td>{{c.account_name}}</td><td>{{c.memo}}</td><td>${{Number(c.amount).toFixed(2)}}</td><td>{{c.status}}</td><td>{{c.print_count}}</td><td><button @click="printCheck(c.id)">Print</button> <button @click="status(c.id,'void')">Void</button> <button @click="status(c.id,'cleared')">Mark Cleared</button></td></tr></tbody></table></div></section>
<section v-if="tab==='accounts'" class="card"><h2>Add Bank Account</h2><label>Nickname<input v-model="account.nickname"></label><label>Account holder<input v-model="account.account_holder"></label><label>Address 1<input v-model="account.address1"></label><label>Address 2<input v-model="account.address2"></label><div class="row"><label>City<input v-model="account.city"></label><label>State<input v-model="account.state"></label><label>ZIP<input v-model="account.postal_code"></label></div><label>Phone<input v-model="account.phone" type="tel"></label><label>Email<input v-model="account.email" type="email"></label><label>Date format<select v-model="account.date_format"><option value="MM/DD/YYYY">MM/DD/YYYY</option><option value="DD/MM/YYYY">DD/MM/YYYY</option><option value="YYYY/MM/DD">YYYY/MM/DD</option><option value="MM-DD-YYYY">MM-DD-YYYY</option></select></label><label>Bank<input v-model="account.bank_name"></label><label>Routing number<input v-model="account.routing_number" inputmode="numeric" maxlength="9" placeholder="9 digits"><small>U.S. routing numbers are exactly 9 digits.</small></label><label>Account number<input v-model="account.account_number" inputmode="numeric" maxlength="34" placeholder="4–34 digits"></label><label>Starting check #<input type="number" v-model="account.next_check_number"></label><button class="primary" @click="addAccount">Add Account</button><hr><p v-for="a in accounts"><b>{{a.nickname}}</b> — {{a.bank_name}} — {{a.account_number_masked}}</p></section>
<section v-if="tab==='payees'" class="card"><h2>Add Payee</h2><label>Name<input v-model="payee.name"></label><label>Address<input v-model="payee.address1"></label><div class="row"><label>City<input v-model="payee.city"></label><label>State<input v-model="payee.state"></label><label>ZIP<input v-model="payee.postal_code"></label></div><button class="primary" @click="addPayee">Add Payee</button><hr><p v-for="p in payees"><button @click="showPayeeHistory(p)">{{p.name}}</button> — {{p.check_count}} checks — ${{Number(p.total_paid).toFixed(2)}}</p><div v-if="selectedPayee"><h3>{{selectedPayee.name}} — Check History</h3><table><thead><tr><th>#</th><th>Date</th><th>Account</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr v-for="c in payeeChecks"><td>{{c.check_number}}</td><td>{{String(c.check_date).slice(0,10)}}</td><td>{{c.account_name}}</td><td>${{Number(c.amount).toFixed(2)}}</td><td>{{c.status}}</td></tr></tbody></table></div></section></main></template>