<script setup>
import{ref,onMounted}from'vue';
const tab=ref('write'),accounts=ref([]),payees=ref([]),checks=ref([]),notice=ref('');
const form=ref({bank_account_id:'',payee_id:'',payee_name:'',amount:'',check_date:new Date().toISOString().slice(0,10),memo:''});
const account=ref({nickname:'',account_holder:'',bank_name:'',routing_number:'',account_number:'',next_check_number:1001});
const payee=ref({name:'',address1:'',city:'',state:'',postal_code:''});
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'Request failed')}return r.json()}
async function load(){[accounts.value,payees.value,checks.value]=await Promise.all([api('/api/accounts'),api('/api/payees'),api('/api/checks')])}
function choose(){const p=payees.value.find(x=>x.id==form.value.payee_id);if(p)form.value.payee_name=p.name}
async function saveCheck(){try{const x=await api('/api/checks',{method:'POST',body:JSON.stringify({...form.value,payee_id:form.value.payee_id||null})});notice.value='Saved check #'+x.check_number;await load()}catch(e){notice.value=e.message}}
async function addAccount(){await api('/api/accounts',{method:'POST',body:JSON.stringify(account.value)});await load()}
async function addPayee(){await api('/api/payees',{method:'POST',body:JSON.stringify(payee.value)});await load()}
async function status(id,s){await api('/api/checks/'+id+'/status',{method:'POST',body:JSON.stringify({status:s})});await load()}
async function printCheck(id){const c=await api('/api/checks/'+id);await status(id,'printed');const w=open('','_blank');const html='<html><head><title>Check '+c.check_number+'</title><style>@page{size:8.5in 3.5in;margin:0}body{font:14px Arial;margin:.25in}.check{width:8in;height:3in;position:relative}.date{position:absolute;right:.2in;top:.15in}.pay{position:absolute;left:.3in;top:1in;font-size:16px}.amount{position:absolute;right:.2in;top:1in;font-size:18px}.words{position:absolute;left:.3in;top:1.45in}.memo{position:absolute;left:.3in;top:2.15in}.micr{position:absolute;bottom:.05in;left:1.2in;font:20px monospace;letter-spacing:2px}</style></head><body><div class="check"><b>'+c.account_holder+'</b><div>'+ (c.payer_address1||'')+'</div><div>'+c.bank_name+'</div><div class="date">'+String(c.check_date).slice(0,10)+' &nbsp; #'+c.check_number+'</div><div class="pay">PAY TO THE ORDER OF: <b>'+c.payee_name+'</b></div><div class="amount">$'+Number(c.amount).toFixed(2)+'</div><div class="words">'+c.amount_words+'</div><div class="memo">Memo: '+(c.memo||'')+'</div><div class="micr">⑆'+c.routing_number+'⑆ ⑈'+c.account_number+'⑈ '+c.check_number+'</div></div></body></html>';w.document.write(html);w.document.close();w.print()}
onMounted(load)
</script>
<template><header><h1>VibeChecks</h1><nav><button v-for="x in ['write','register','accounts','payees']" @click="tab=x" :class="{active:tab===x}">{{x}}</button></nav></header><main><p class="notice" v-if="notice">{{notice}}</p>
<section v-if="tab==='write'" class="card"><h2>Write Check</h2><label>Bank account<select v-model="form.bank_account_id"><option value="">Select</option><option v-for="a in accounts" :value="a.id">{{a.nickname}} — next #{{a.next_check_number}}</option></select></label><label>Saved payee<select v-model="form.payee_id" @change="choose"><option value="">Custom</option><option v-for="p in payees" :value="p.id">{{p.name}}</option></select></label><label>Pay to<input v-model="form.payee_name"></label><div class="row"><label>Amount<input type="number" step=".01" v-model="form.amount"></label><label>Date<input type="date" v-model="form.check_date"></label></div><label>Memo<input v-model="form.memo"></label><button class="primary" @click="saveCheck">Save Check</button></section>
<section v-if="tab==='register'" class="card wide"><h2>Check Register</h2><table><thead><tr><th>#</th><th>Date</th><th>Payee</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="c in checks"><td>{{c.check_number}}</td><td>{{String(c.check_date).slice(0,10)}}</td><td>{{c.payee_name}}</td><td>{{Number(c.amount).toFixed(2)}}</td><td>{{c.status}}</td><td><button @click="printCheck(c.id)">Print</button> <button @click="status(c.id,'void')">Void</button> <button @click="status(c.id,'cleared')">Clear</button></td></tr></tbody></table></section>
<section v-if="tab==='accounts'" class="card"><h2>Add Bank Account</h2><label>Nickname<input v-model="account.nickname"></label><label>Account holder<input v-model="account.account_holder"></label><label>Bank<input v-model="account.bank_name"></label><label>Routing number<input v-model="account.routing_number"></label><label>Account number<input v-model="account.account_number"></label><label>Starting check #<input type="number" v-model="account.next_check_number"></label><button class="primary" @click="addAccount">Add Account</button><hr><p v-for="a in accounts"><b>{{a.nickname}}</b> — {{a.bank_name}} — {{a.account_number_masked}}</p></section>
<section v-if="tab==='payees'" class="card"><h2>Add Payee</h2><label>Name<input v-model="payee.name"></label><label>Address<input v-model="payee.address1"></label><div class="row"><label>City<input v-model="payee.city"></label><label>State<input v-model="payee.state"></label><label>ZIP<input v-model="payee.postal_code"></label></div><button class="primary" @click="addPayee">Add Payee</button><hr><p v-for="p in payees">{{p.name}}</p></section></main></template>