<script setup>
import{ref,onMounted}from'vue';
const tab=ref('write'),accounts=ref([]),payees=ref([]),checks=ref([]),notice=ref('');
const form=ref({bank_account_id:'',payee_id:'',payee_name:'',amount:'',check_date:new Date().toISOString().slice(0,10),memo:''});
const account=ref({nickname:'',account_holder:'',bank_name:'',routing_number:'',account_number:'',next_check_number:1001});
const payee=ref({name:'',address1:'',city:'',state:'',postal_code:''});
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'Request failed')}return r.json()}
async function load(){[accounts.value,payees.value,checks.value]=await Promise.all([api('/api/accounts'),api('/api/payees'),api('/api/checks')])}
function choose(){const p=payees.value.find(x=>x.id==form.value.payee_id);if(p)form.value.payee_name=p.name}
async function saveCheck(){try{const x=await api('/api/checks',{method:'POST',body:JSON.stringify({...form.value,payee_id:form.value.payee_id||null})});notice.value='Saved check #'+x.check_number;await load()}catch(e){notice.value=e.message}}
async function addAccount(){notice.value='';try{await api('/api/accounts',{method:'POST',body:JSON.stringify(account.value)});notice.value='Bank account added';account.value={nickname:'',account_holder:'',bank_name:'',routing_number:'',account_number:'',next_check_number:1001};await load()}catch(e){notice.value=e.message}}
async function addPayee(){try{await api('/api/payees',{method:'POST',body:JSON.stringify(payee.value)});await load()}catch(e){notice.value=e.message}}
async function status(id,s){await api('/api/checks/'+id+'/status',{method:'POST',body:JSON.stringify({status:s})});await load()}
async function printCheck(id){
 const c=await api('/api/checks/'+id),w=open('','_blank');if(!w){notice.value='Pop-up blocked. Allow pop-ups to print.';return}
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const html=`<!doctype html><html><head><title>Check ${esc(c.check_number)}</title><style>
 @page{size:8.5in 11in;margin:0}*{box-sizing:border-box}html,body{margin:0!important;padding:0!important;width:8.5in!important;height:11in!important}body{font-family:Arial,sans-serif;color:#000;overflow:hidden}
 .sheet{position:relative;width:8.5in;height:11in}.check{position:absolute;left:0;top:0;width:8.5in;height:3.5in}.stub{position:absolute;left:0;top:3.5in;width:8.5in;height:3.5in;padding:.28in .55in;font-size:9pt}.stub-company{position:absolute;left:.55in;top:.25in;font-weight:bold;font-size:10pt}.stub-checkno{position:absolute;right:.55in;top:.22in;font-size:11pt}.stub-payee{position:absolute;left:.85in;top:.62in;font-size:10pt;font-weight:bold}.stub-grid{position:absolute;left:.55in;right:.55in;top:1.02in;display:grid;grid-template-columns:.72in .62in 1.0in 1.12in 1.12in .82in 1.05in;column-gap:.08in;text-align:right}.stub-grid>div:nth-child(1),.stub-grid>div:nth-child(2),.stub-grid>div:nth-child(3){text-align:left}.stub-label{font-size:8pt;color:#333;line-height:1.05}.stub-value{font-size:9pt;padding-top:.08in}.stub-total-label{position:absolute;right:1.65in;top:1.72in;font-size:9pt}.stub-total{position:absolute;right:.62in;top:1.72in;width:.9in;text-align:right;font-size:9pt}.stub-account{position:absolute;left:.55in;bottom:.35in;font-size:9pt}.stub-bottom-total{position:absolute;right:.62in;bottom:.35in;width:.9in;text-align:right;font-size:9pt}
 .payer{position:absolute;left:.45in;top:.28in;font-size:9pt;line-height:1.15}.bank{position:absolute;left:3.25in;top:.28in;font-size:8pt}.number{position:absolute;right:.40in;top:.25in;font-size:10pt;font-weight:bold}.date{position:absolute;right:.45in;top:.72in;font-size:9pt}
 .paylabel{position:absolute;left:.38in;top:1.12in;font-size:7pt;line-height:1.1}.payee{position:absolute;left:1.25in;right:1.55in;top:1.08in;height:.30in;border-bottom:1px solid #000;padding:.03in .08in;font-size:10pt;font-weight:bold}
 .amount{position:absolute;right:.38in;top:1.08in;width:1.12in;height:.30in;border:1px solid #000;padding:.04in .08in;text-align:right;font-size:10pt;font-weight:bold}.words{position:absolute;left:.38in;right:.38in;top:1.52in;height:.32in;border-bottom:1px solid #000;padding:.04in .08in;font-size:9pt}
 .memo{position:absolute;left:.45in;top:2.18in;font-size:8pt}.micr{position:absolute;left:.72in;bottom:.18in;font-family:E13B,OCRB,monospace;font-size:14pt;letter-spacing:.025in;white-space:nowrap}
 </style></head><body><div class="sheet"><div class="check"><div class="payer"><b>${esc(c.account_holder)}</b><br>${esc(c.payer_address1||'')}</div><div class="bank">${esc(c.bank_name)}</div><div class="number">#${esc(c.check_number)}</div><div class="date">${esc(String(c.check_date).slice(0,10))}</div><div class="paylabel">PAY TO THE<br>ORDER OF</div><div class="payee">${esc(c.payee_name)}</div><div class="amount">$${Number(c.amount).toFixed(2)}</div><div class="words">${esc(c.amount_words)}</div><div class="memo">Memo: ${esc(c.memo||'')}</div><div class="micr">⑆${esc(c.routing_number)}⑆ &nbsp;⑈${esc(c.account_number)}⑈ &nbsp;${esc(c.check_number)}</div></div><div class="stub"><div class="stub-title">${esc(c.account_holder)}</div><div class="stub-grid"><div class="stub-label">DATE</div><div class="stub-label">COMPANY / PAYEE</div><div class="stub-label">REFERENCE #</div><div class="stub-label">CHECK AMOUNT</div><div class="stub-value">${esc(String(c.check_date).slice(0,10))}</div><div class="stub-value">${esc(c.payee_name)}</div><div class="stub-value">${esc(c.check_number)}</div><div class="stub-value">${Number(c.amount).toFixed(2)}</div></div><div class="stub-note">Memo: ${esc(c.memo||"")}</div></div></div></body></html>`;
 w.document.write(html);w.document.close();w.focus();setTimeout(()=>{w.print();status(id,'printed')},350)
}
onMounted(load)
</script>
<template><header><h1>VibeChecks</h1><nav><button v-for="x in ['write','register','accounts','payees']" @click="tab=x" :class="{active:tab===x}">{{x}}</button></nav></header><main><p class="notice" v-if="notice">{{notice}}</p>
<section v-if="tab==='write'" class="card"><h2>Write Check</h2><label>Bank account<select v-model="form.bank_account_id"><option value="">Select</option><option v-for="a in accounts" :value="a.id">{{a.nickname}} — next #{{a.next_check_number}}</option></select></label><label>Saved payee<select v-model="form.payee_id" @change="choose"><option value="">Custom</option><option v-for="p in payees" :value="p.id">{{p.name}}</option></select></label><label>Pay to<input v-model="form.payee_name"></label><div class="row"><label>Amount<input type="number" step=".01" v-model="form.amount"></label><label>Date<input type="date" v-model="form.check_date"></label></div><label>Memo<input v-model="form.memo"></label><button class="primary" @click="saveCheck">Save Check</button></section>
<section v-if="tab==='register'" class="card wide"><h2>Check Register</h2><table><thead><tr><th>#</th><th>Date</th><th>Payee</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="c in checks"><td>{{c.check_number}}</td><td>{{String(c.check_date).slice(0,10)}}</td><td>{{c.payee_name}}</td><td>{{Number(c.amount).toFixed(2)}}</td><td>{{c.status}}</td><td><button @click="printCheck(c.id)">Print</button> <button @click="status(c.id,'void')">Void</button> <button @click="status(c.id,'cleared')">Clear</button></td></tr></tbody></table></section>
<section v-if="tab==='accounts'" class="card"><h2>Add Bank Account</h2><label>Nickname<input v-model="account.nickname"></label><label>Account holder<input v-model="account.account_holder"></label><label>Bank<input v-model="account.bank_name"></label><label>Routing number<input v-model="account.routing_number" inputmode="numeric" maxlength="9" placeholder="9 digits"><small>U.S. routing numbers are exactly 9 digits.</small></label><label>Account number<input v-model="account.account_number" inputmode="numeric" maxlength="34" placeholder="4–34 digits"></label><label>Starting check #<input type="number" v-model="account.next_check_number"></label><button class="primary" @click="addAccount">Add Account</button><hr><p v-for="a in accounts"><b>{{a.nickname}}</b> — {{a.bank_name}} — {{a.account_number_masked}}</p></section>
<section v-if="tab==='payees'" class="card"><h2>Add Payee</h2><label>Name<input v-model="payee.name"></label><label>Address<input v-model="payee.address1"></label><div class="row"><label>City<input v-model="payee.city"></label><label>State<input v-model="payee.state"></label><label>ZIP<input v-model="payee.postal_code"></label></div><button class="primary" @click="addPayee">Add Payee</button><hr><p v-for="p in payees">{{p.name}}</p></section></main></template>
